"""Evidence is generated by actual successful tool calls, not model assertions."""
import hashlib
import json
import os
from pathlib import Path
import re
import tempfile
import time

PREFIXES = {"agentmail": "agentmail", "composio": "composio", "pandadoc": "pandadoc",
            "super_browser": "super-browser", "scrapecreators": "scrapecreators", "agent_cards": "agentcard"}


def on_tool(**kwargs):
    name = str(kwargs.get("tool_name", "")).lower().replace("-", "_")
    if kwargs.get("status") not in {"success", "ok"}:
        return
    # Only a successful read-style capability can count. A configured server or
    # tool-list discovery has a different name and cannot satisfy this observer.
    if not re.search(r"(?:^|_)(get|list|search|fetch|read|scrape|browse|extract|lookup|whoami|check)(?:_|$)", name):
        return
    service = next((value for key, value in PREFIXES.items() if name.startswith("mcp__" + key + "__")), None)
    if not service:
        return
    result = kwargs.get("result")
    if not result:
        return
    from hermes_constants import get_hermes_home
    folder = Path(get_hermes_home()) / ".orgo-onboarding"
    folder.mkdir(mode=0o700, parents=True, exist_ok=True)
    try:
        from gateway.platforms._shared import get_scoped_secret
        import yaml
        contract = json.loads((folder / "connection-contracts.json").read_text())[service]
        def digest(value):
            return hashlib.sha256(json.dumps(value, sort_keys=True, separators=(",", ":")).encode()).hexdigest()
        actual = {key: get_scoped_secret(key) or "" for key in contract["keys"]}
        config = yaml.safe_load((Path(get_hermes_home()) / "config.yaml").read_text()) or {}
        if digest(actual) != contract["credentials"] or digest(config.get("mcp_servers", {}).get(contract["mcp_name"], {})) != contract["mcp"]:
            return
        value = json.loads(result) if isinstance(result, str) else result
        if isinstance(value, dict) and (value.get("isError") or value.get("error") or value.get("success") is False):
            return
    except (OSError, ValueError, KeyError, TypeError):
        return
    proof = {"connection": contract["fingerprint"],"schema_version": 1, "verified_at": int(time.time()), "tool": name,
             "result_hash": hashlib.sha256(str(result).encode()).hexdigest()}
    if service == "agentcard":
        if not actual.get("AGENTCARD_API_KEY", "").startswith("sk_test_"):
            return
        proof["mode"] = "TEST"
    fd, path = tempfile.mkstemp(dir=folder, prefix=".capability-")
    try:
        with os.fdopen(fd, "w") as stream:
            os.fchmod(stream.fileno(), 0o600)
            json.dump(proof, stream)
        os.replace(path, folder / (service + "-capability.json"))
    finally:
        Path(path).unlink(missing_ok=True)


def register(ctx):
    ctx.register_hook("post_tool_call", on_tool)
